package com.movitech.mbox.modules.wdt.taskStatus.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskCancel;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskCancelExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TaskCancelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int countByExample(TaskCancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByExample(TaskCancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insert(TaskCancel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insertSelective(TaskCancel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    List<TaskCancel> selectByExample(TaskCancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    TaskCancel selectByPrimaryKey(String id);
    
    TaskCancel selectByTaskId(String id);
    
    

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskCancel record, @Param("example") TaskCancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExample(@Param("record") TaskCancel record, @Param("example") TaskCancelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKeySelective(TaskCancel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_cancel
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKey(TaskCancel record);
}