package com.movitech.mbox.modules.wdt.taskStatus.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskExtension;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskExtensionExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TaskExtensionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int countByExample(TaskExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByExample(TaskExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insert(TaskExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insertSelective(TaskExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    List<TaskExtension> selectByExample(TaskExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    TaskExtension selectByPrimaryKey(String id);

    TaskExtension selectByTaskId(String id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskExtension record, @Param("example") TaskExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExample(@Param("record") TaskExtension record, @Param("example") TaskExtensionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKeySelective(TaskExtension record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_extension
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKey(TaskExtension record);
}