package com.movitech.mbox.modules.wdt.taskStatus.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskPause;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskPauseExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TaskPauseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int countByExample(TaskPauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByExample(TaskPauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insert(TaskPause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insertSelective(TaskPause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    List<TaskPause> selectByExample(TaskPauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    TaskPause selectByPrimaryKey(String id);
    
    TaskPause selectByTaskId(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskPause record, @Param("example") TaskPauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExample(@Param("record") TaskPause record, @Param("example") TaskPauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKeySelective(TaskPause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_pause
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKey(TaskPause record);
}