package com.movitech.mbox.modules.wdt.taskStatus.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskBanjie;
import com.movitech.mbox.modules.wdt.taskStatus.entity.TaskBanjieExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TaskBanjieMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int countByExample(TaskBanjieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByExample(TaskBanjieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insert(TaskBanjie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int insertSelective(TaskBanjie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    List<TaskBanjie> selectByExample(TaskBanjieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    TaskBanjie selectByPrimaryKey(String id);
    
    
    TaskBanjie selectByTaskId(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskBanjie record, @Param("example") TaskBanjieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByExample(@Param("record") TaskBanjie record, @Param("example") TaskBanjieExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKeySelective(TaskBanjie record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_banjie_log
     *
     * @mbggenerated Mon Aug 14 16:13:04 CST 2017
     */
    int updateByPrimaryKey(TaskBanjie record);
}