package com.movitech.mbox.modules.wdt.operateLog.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.operateLog.entity.OperateLog;
import com.movitech.mbox.modules.wdt.operateLog.entity.OperateLogExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface OperateLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int countByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int deleteByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int insert(OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int insertSelective(OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    List<OperateLog> selectByExample(OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    OperateLog selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int updateByExampleSelective(@Param("record") OperateLog record, @Param("example") OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int updateByExample(@Param("record") OperateLog record, @Param("example") OperateLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int updateByPrimaryKeySelective(OperateLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_operate_log
     *
     * @mbggenerated Tue Aug 22 10:40:14 CST 2017
     */
    int updateByPrimaryKey(OperateLog record);
}