package com.movitech.mbox.modules.wdt.taskProject.entity;

import java.io.Serializable;
import java.util.Date;

public class TaskProject implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.task_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String taskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.project_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.name
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.create_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String createBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.create_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.update_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String updateBy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.update_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wdt_t_task_project.del_flag
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.id
     *
     * @return the value of wdt_t_task_project.id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.id
     *
     * @param id the value for wdt_t_task_project.id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.task_id
     *
     * @return the value of wdt_t_task_project.task_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.task_id
     *
     * @param taskId the value for wdt_t_task_project.task_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId == null ? null : taskId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.project_id
     *
     * @return the value of wdt_t_task_project.project_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.project_id
     *
     * @param projectId the value for wdt_t_task_project.project_id
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setProjectId(String projectId) {
        this.projectId = projectId == null ? null : projectId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.name
     *
     * @return the value of wdt_t_task_project.name
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.name
     *
     * @param name the value for wdt_t_task_project.name
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.create_by
     *
     * @return the value of wdt_t_task_project.create_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getCreateBy() {
        return createBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.create_by
     *
     * @param createBy the value for wdt_t_task_project.create_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setCreateBy(String createBy) {
        this.createBy = createBy == null ? null : createBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.create_date
     *
     * @return the value of wdt_t_task_project.create_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.create_date
     *
     * @param createDate the value for wdt_t_task_project.create_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.update_by
     *
     * @return the value of wdt_t_task_project.update_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getUpdateBy() {
        return updateBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.update_by
     *
     * @param updateBy the value for wdt_t_task_project.update_by
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy == null ? null : updateBy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.update_date
     *
     * @return the value of wdt_t_task_project.update_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.update_date
     *
     * @param updateDate the value for wdt_t_task_project.update_date
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wdt_t_task_project.del_flag
     *
     * @return the value of wdt_t_task_project.del_flag
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wdt_t_task_project.del_flag
     *
     * @param delFlag the value for wdt_t_task_project.del_flag
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        TaskProject other = (TaskProject) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getName() == null ? other.getName() == null : this.getName().equals(other.getName()))
            && (this.getCreateBy() == null ? other.getCreateBy() == null : this.getCreateBy().equals(other.getCreateBy()))
            && (this.getCreateDate() == null ? other.getCreateDate() == null : this.getCreateDate().equals(other.getCreateDate()))
            && (this.getUpdateBy() == null ? other.getUpdateBy() == null : this.getUpdateBy().equals(other.getUpdateBy()))
            && (this.getUpdateDate() == null ? other.getUpdateDate() == null : this.getUpdateDate().equals(other.getUpdateDate()))
            && (this.getDelFlag() == null ? other.getDelFlag() == null : this.getDelFlag().equals(other.getDelFlag()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getName() == null) ? 0 : getName().hashCode());
        result = prime * result + ((getCreateBy() == null) ? 0 : getCreateBy().hashCode());
        result = prime * result + ((getCreateDate() == null) ? 0 : getCreateDate().hashCode());
        result = prime * result + ((getUpdateBy() == null) ? 0 : getUpdateBy().hashCode());
        result = prime * result + ((getUpdateDate() == null) ? 0 : getUpdateDate().hashCode());
        result = prime * result + ((getDelFlag() == null) ? 0 : getDelFlag().hashCode());
        return result;
    }
}