package com.movitech.mbox.modules.wdt.taskProject.dao;

import com.movitech.mbox.common.persistence.annotation.MyBatisDao;
import com.movitech.mbox.modules.wdt.taskProject.entity.TaskProject;
import com.movitech.mbox.modules.wdt.taskProject.entity.TaskProjectExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;
@MyBatisDao
public interface TaskProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int countByExample(TaskProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int deleteByExample(TaskProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int insert(TaskProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int insertSelective(TaskProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    List<TaskProject> selectByExample(TaskProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    TaskProject selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int updateByExampleSelective(@Param("record") TaskProject record, @Param("example") TaskProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int updateByExample(@Param("record") TaskProject record, @Param("example") TaskProjectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int updateByPrimaryKeySelective(TaskProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wdt_t_task_project
     *
     * @mbggenerated Tue Aug 29 15:01:59 CST 2017
     */
    int updateByPrimaryKey(TaskProject record);
}